version: "2"

run:
  timeout: 5m
  build-tags:
    - integration
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - errorlint
    - copyloopvar
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - exhaustive
  settings:
    revive:
      # Sans cette option, la liste « rules » remplace les règles par défaut
      enable-default-rules: true
      rules:
        - name: comment-spacings
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - goconst

formatters:
  enable:
    - goimports
    - golines
    - gofumpt
  settings:
    gofumpt:
      module-path: gsontag.fr/kforward
      extra:
        group-params: true
        balance-calls: true
        clothe-returns: true
    golines:
      max-len: 120
      shorten-comments: true
      tab-len: 4
    goimports:
      local-prefixes:
        - gsontag.fr/kforward